# Camera settings
camera0: http://192.168.1.185:81/stream                      # Camera index for first camera
camera1: 1                           # Camera index for second camera, stereo vision
#stereocamera_id: 0                  # Placeholder for future stereo calibration
frame_width: 1920                    # Frame width
frame_height: 1080                   # Frame height
mono_calibration_frames: 10          # Number of frames to capture for calibration
#stereo_calibration_frames: 10       # Placeholder for future stereo calibration with dual cameras
view_resize: 2                       # Resize factor for display purposes. Want greater than 1
cooldown: 100                        # Ticks to wait before next frame
img_dir: 'frames'                    # Directory where captured frames are located
n_frames: 10                         # Number of frames to capture

# Checkerboard settings
checkerboard_box_size_scale : 0.0319 # m side length for each square
checkerboard_row_vertices: 4         # Number of Checkerboard row intersections (rows-1)
checkerboard_column_vertices: 7      # Number of Checkerboard column intersections (columns-1)

# ArUCo marker parameters
aruco_size: 0.015                     # Size of the aruco marker in meters
